name: Compress JPG to WEBP and Deploy

on:
  push:
    branches:
      - main

jobs:
  compress_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Compress JPG to WEBP
        run: |
          mkdir -p webp
          for img in *.jpg; do
            convert "$img" -quality 80 "webp/${img%.jpg}.webp"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webp